global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'self'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter_wsl'
    static_configs:
      - targets: ['172.31.241.22:9100']